[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
todo_solana = "sA62Db23P2TJsM9UBV6JDNSG3L4esgdxFcM5norjfv4"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.devnet.solana.com"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
